[package]
name = "simple_http"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "simple_http"
path = "src/bin/simple_http.rs"

[lib]
name = "http_lib"
path = "src/lib.rs"


[dependencies]
env_logger = "0.11"
log = "0.4"
anyhow = "1.0"
